### ISSUE TITLE
百度分享打开用不了呢

### ISSUE THREAD

**Issue by ws1227** [iissnan/hexo-theme-next#1659] opened 2017-05-09 08:12 UTC
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by heqiang421** [comment] 2017-05-10 15:38
应该是百度分享不支持https,我选择用jiathis

**Comment by ehlxr** [comment] 2017-05-11 01:13
jiathis 也不支持 https 吧，[百度分享不支持Https的解决方案](https://github.com/hrwhisper/baiduSharehttps://github.com/hrwhisper/baiduShare)

**Comment by ivan-nginx** [comment] 2017-07-20 03:55
@ws1227 don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Haocen** [comment] 2017-09-18 18:11
The problem is about Baidu, a search engine similar with Google, this issue is inappropriate to open in this repository.

**Closed** 2017-09-18 18:16 UTC

**Comment by ivan-nginx** [comment] 2017-09-18 18:19
#1592.
