### ISSUE TITLE
修改后报错

### ISSUE THREAD

**Issue by anlwy** [iissnan/hexo-theme-next#1958] opened 2017-10-19 15:52 UTC
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/hexo/. Press Ctrl+C to stop.
Unhandled rejection Error: ENOENT: no such file or directory, open 'E:\a\themes\hexo\layout\_macro\my-copyright.swig'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at Object.ret.load (E:\a\node_modules\swig\lib\loaders\filesystem.js:55:15)
    at compileFile (E:\a\node_modules\swig\lib\swig.js:695:31)
    at Object._ctx.post_template.render (eval at <anonymous> (E:\a\node_modules\swig\lib\swig.js:498:13), <anonymous>:447:18)
    at Object.eval [as tpl] (eval at <anonymous> (E:\a\node_modules\swig\lib\swig.js:498:13), <anonymous>:850:1078)
    at compiled (E:\a\node_modules\swig\lib\swig.js:619:18)
    at _compiled (E:\a\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (E:\a\node_modules\hexo\lib\theme\view.js:29:15)
    at E:\a\node_modules\hexo\lib\hexo\index.js:390:25
    at tryCatcher (E:\a\node_modules\bluebird\js\release\util.js:16:23)
    at E:\a\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\a\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Unhandled rejection Error: ENOENT: no such file or directory, open 'E:\a\themes\hexo\layout\_macro\my-copyright.swig'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at Object.ret.load (E:\a\node_modules\swig\lib\loaders\filesystem.js:55:15)
    at compileFile (E:\a\node_modules\swig\lib\swig.js:695:31)
    at Object._ctx.post_template.render (eval at <anonymous>

**Comment by anlwy** [comment] 2017-10-19 15:52
{% if page.copyright %}
<div class="my_post_copyright">
  <script src="//cdn.bootcss.com/clipboard.js/1.5.10/clipboard.min.js"></script>

  
  <script type="text/javascript" src="http://jslibs.wuxubj.cn/sweetalert_mini/jquery-1.7.1.min.js"></script>
  <script src="http://jslibs.wuxubj.cn/sweetalert_mini/sweetalert.min.js"></script>
  <link rel="stylesheet" type="text/css" href="http://jslibs.wuxubj.cn/sweetalert_mini/sweetalert.mini.css">
  <p><span>本文标题:</span><a href="{{ url_for(page.path) }}">{{ page.title }}</a></p>
  <p><span>文章作者:</span><a href="/" title="访问 {{ theme.author }} 的个人博客">{{ theme.author }}</a></p>
  <p><span>发布时间:</span>{{ page.date.format("YYYY年MM月DD日 - HH:MM") }}</p>
  <p><span>最后更新:</span>{{ page.updated.format("YYYY年MM月DD日 - HH:MM") }}</p>
  <p><span>原始链接:</span><a href="{{ url_for(page.path) }}" title="{{ page.title }}">{{ page.permalink }}</a>
    <span class="copy-path"  title="点击复制文章链接"><i class="fa fa-clipboard" data-clipboard-text="{{ page.permalink }}"  aria-label="复制成功！"></i></span>
  </p>
  <p><span>许可协议:</span><i class="fa fa-creative-commons"></i> <a rel="license" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" title="Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)">署名-非商业性使用-禁止演绎 4.0 国际</a> 转载请保留原文链接及作者。</p>  
</div>
<script> 
    var clipboard = new Clipboard('.fa-clipboard');
    clipboard.on('success', $(function(){
      $(".fa-clipboard").click(function(){
        swal({   
          title: "",   
          text: '复制成功',   
          html: false,
          timer: 500,   
          showConfirmButton: false
        });
      });
    }));  
</script>
{% endif %}

**Comment by anlwy** [comment] 2017-10-19 15:53
{% if page.copyright %}
<div class="my_post_copyright">
  <script src="//cdn.bootcss.com/clipboard.js/1.5.10/clipboard.min.js"></script>

  
  <script type="text/javascript" src="http://jslibs.wuxubj.cn/sweetalert_mini/jquery-1.7.1.min.js"></script>
  <script src="http://jslibs.wuxubj.cn/sweetalert_mini/sweetalert.min.js"></script>
  <link rel="stylesheet" type="text/css" href="http://jslibs.wuxubj.cn/sweetalert_mini/sweetalert.mini.css">
  <p><span>本文标题:</span><a href="{{ url_for(page.path) }}">{{ page.title }}</a></p>
  <p><span>文章作者:</span><a href="/" title="访问 {{ theme.author }} 的个人博客">{{ theme.author }}</a></p>
  <p><span>发布时间:</span>{{ page.date.format("YYYY年MM月DD日 - HH:MM") }}</p>
  <p><span>最后更新:</span>{{ page.updated.format("YYYY年MM月DD日 - HH:MM") }}</p>
  <p><span>原始链接:</span><a href="{{ url_for(page.path) }}" title="{{ page.title }}">{{ page.permalink }}</a>
    <span class="copy-path"  title="点击复制文章链接"><i class="fa fa-clipboard" data-clipboard-text="{{ page.permalink }}"  aria-label="复制成功！"></i></span>
  </p>
  <p><span>许可协议:</span><i class="fa fa-creative-commons"></i> <a rel="license" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" title="Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)">署名-非商业性使用-禁止演绎 4.0 国际</a> 转载请保留原文链接及作者。</p>  
</div>
<script> 
    var clipboard = new Clipboard('.fa-clipboard');
    clipboard.on('success', $(function(){
      $(".fa-clipboard").click(function(){
        swal({   
          title: "",   
          text: '复制成功',   
          html: false,
          timer: 500,   
          showConfirmButton: false
        });
      });
    }));  
</script>
{% endif %}

**Comment by ivan-nginx** [comment] 2017-10-25 05:57
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by zhichengMLE** [comment] 2017-11-02 11:09
I believe the top #1 and #2 comment are trying to explain what he did to cause the error @ivan-nginx   --> He tried to add another copy-right for article. 

I think the problem is he had add the file in a wrong directory. (Unhandled rejection Error: ENOENT: no such file or directory, open 'E:\a\themes\hexo\layout_macro\my-copyright.swig')

Note that I am not familiar with front-end programming. Please correct me if I was wrong.

**Comment by ivan-nginx** [comment] 2017-11-02 11:34
@zhichengMLE thank's for translate. And, yes, `layout_macro` — isn't right path for NexT theme. It must be `layout/macro`.

Issue will be closed due not enought information.

**Closed by ivan-nginx** 2017-11-02 11:34 UTC
Labels: Wait for Answer
